### ISSUE TITLE
Deixar a ordem compatível com a urna

### ISSUE THREAD

**Issue by joaoarthurbm** [lucis/meu-santinho#21]
No dia da votação a ordem estabelecida é: federal, estadual, senador, governador e presidente. A ordem no santinho está diferente e acredito que pode confundir o eleitor.

**Comment by lucis** [comment]
@soutofernando vc tá trabalhando nisso já, correto?

Pode colocar um PR com a mudança de código, que eu faço a mudança nos arquivos PNG de template e subimos junto.
